### ISSUE TITLE
can't find it on Yarn

### ISSUE THREAD

**Issue by javieraviles** [kuhnroyal/mat-datetimepicker#1]
Hello!

I am very interested in this component, looks really interesting,  but I can't find it on Yarn as the Readme file specifies... is there any other way I can import this component in my project?

**Comment by kuhnroyal** [comment]
I just published it on the npm registry. It was not published so far, as the README stated ;)
Give it a try.

**Comment by javieraviles** [comment]
Working like a charm in a Firebase-Angular5-Material project, trying out Spanish internationalization, enough with MatNativeDatetimeModule. Thank you so much!!!!!!

![image](https://user-images.githubusercontent.com/8101719/34034904-a273bde0-e180-11e7-92c3-f2944165dc8d.png)
