### ISSUE TITLE
mat-datetimepicker keep opening

### ISSUE THREAD

**Issue by kyawkhaing** [kuhnroyal/mat-datetimepicker#10]
I am using latest version 1.0.2 , I am facing one issue in the ie 11, when click in the text box, instead of clicking on the calendar icon , Calendar popup comes up but after choosing the date popup close and open again, keep happening like this.Can't close totally.  Even though I call datetimepicker.close() function, behaviour still the same. When I called datetimepicker.close(), calendar popup close and open back again.Please advise me what to do.It already took 3 hours to fix it but can't.
Thanks.

**Comment by kuhnroyal** [comment]
Maybe I can look at this at the weekend, not sure I find an IE11 somewhere tho.
Do me a favor and see if the datetimepicker here works in IE11: http://code.promactinfo.com/md2/#/datepicker

**Comment by kuhnroyal** [comment]
Fixed by 0e67e30b2734985b8dddaa72b03bf1dff70c6b84
