### ISSUE TITLE
A 'time' type for the mat-datetimepicker component reports a form error when the time is typed in the input element

### ISSUE THREAD

**Issue by benoitbzl** [kuhnroyal/mat-datetimepicker#11]
The time format reported is for example (for `en-US` local) like "12:58 AM". This format is not recognized by the native date format obviously.
Using the `momentjs` format, it should work, but there is a limitation in the code that don't select a correct `momentjs` parsing format string for time only.

I will propose a PR to fix that issue.

**Comment by Mctalian** [comment]
I believe I'm having this problem as well. When a user types into the input field 12:58 AM, and then you click on the field to open the DateTimePicker, it shows "00:00" for the time. Same issue, I presume, and your PR would fix it?

**Comment by benoitbzl** [comment]
Yes I believe this is the same issue. You can test my fix using my branches npm-core and npm-moment that contain the npm packages with my fix.
You can use them in your package.json file as:
    "@mat-datetimepicker/core": "git+https://git@github.com/benoitbzl/mat-datetimepicker.git#npm-core",
    "@mat-datetimepicker/moment": "git+https://git@github.com/benoitbzl/mat-datetimepicker.git#npm-moment",

**Comment by Mctalian** [comment]
@benoitbzl Sadly, that doesn't seem to fix my issue. But I did have some trouble getting the install working. My console kept closing after I issued the command
