### ISSUE TITLE
PatchValue on reactive forms not setting value

### ISSUE THREAD

**Issue by JadedEric** [kuhnroyal/mat-datetimepicker#113]
Hi.

I'm running into an issue where .patchValue(..) on my form's not setting the value in the datetimepicker display in the front-end and I'm unsure way, as the value is definitely in the form:

![image](https://user-images.githubusercontent.com/1898304/88969567-55dfdc00-d2b1-11ea-9ae5-9599a3490020.png)

however, in the front-end, nothing:

![image](https://user-images.githubusercontent.com/1898304/88969600-642df800-d2b1-11ea-9385-c637b616b909.png)

I'm on Angular 10, with the latest update on Material.

**Comment by Murena7** [comment]
Same issue

**Comment by alfaproject** [comment]
I think my latest PR fixes this issue, feel free to patch it locally to test it out https://github.com/kuhnroyal/mat-datetimepicker/pull/285

**Comment by bbortt** [comment]
fixed in [`v0.9.36`](https://github.com/kuhnroyal/mat-datetimepicker/releases/tag/v9.0.36).
