### ISSUE TITLE
Material >=10.2.0

### ISSUE THREAD

**Issue by Eugeno** [kuhnroyal/mat-datetimepicker#115]
`ng update @angular/material`
🔻
`Package "@mat-datetimepicker/core" has an incompatible peer dependency to "@angular/cdk" (requires "~10.1.1", would install "10.2.3").`
`× Migration failed: Incompatible peer dependencies found.`

**Comment by Eugeno** [comment]
Also, need support for @angular/material >=10.2.x

**Comment by bbortt** [comment]
can be tested in `5.1.0-0` (`beta`).
