### ISSUE TITLE
Inconsistency between Core/Moment CDK and Material versions

### ISSUE THREAD

**Issue by oupablo** [kuhnroyal/mat-datetimepicker#120]
mat-datetimepicker/core has peer deps for:
"@angular/cdk": "^10.2.3",
"@angular/material": "^10.2.3"

mat-datetimepicker/moment has peer deps for:
"@angular/cdk": "^10.1.1",
"@angular/material": "^10.1.1"

This issue is seen in version 5.1.1 and was also in version 5.0.1

**Comment by bbortt** [comment]
I think this doesn't really matter, right? the carret symbol (`^`) indicates everything up to (but without) `11.0.0` is fine.. I agree it is not very nice, but doesn't have an impact on users. or did you experience troubles?
feel free to create a PR tho, it's a quick fix!

**Comment by oupablo** [comment]
I agree on the ^ symbol. It should be fine. Running npm install was throwing a peer dependency error for me though until I edited the moment library to match. Not sure exactly why it's not valid but I submitted a PR to make core and moment match.

**Comment by bbortt** [comment]
Ah, I see. `peerDependencies` use the tilde `~` sign which does only match patches. thx for the PR!

**Comment by bbortt** [comment]
@oupablo released just a moment ago in `5.1.2`. thx.
