### ISSUE TITLE
Feature request: custom icons for mat-datetimepicker-toggle

### ISSUE THREAD

**Issue by AndyInfin** [kuhnroyal/mat-datetimepicker#123]
Modules versions:
"@angular/material": "9.2.1",
"@mat-datetimepicker/core": "5.1.1",
"@mat-datetimepicker/moment": "5.1.1"

Trying to do custom icon similar to original mat-datepicker:
`<mat-datetimepicker-toggle [for]="datetimePicker" matSuffix>`
`	<span class="icons icon-calendar" matDatepickerToggleIcon></span>`
`</mat-datetimepicker-toggle>`

But this didn't work. Can you provide this feature, or can we set custom calendar toggle icon in some other way?

**Comment by bbortt** [comment]
you are welcome to open a pull request .. unfortunately i don't have time myself at the moment..

**Comment by AndyInfin** [comment]
Done this by delete mat-datepicker-toggle from template and add
`<span class="icons icon-calendar clickable" matSuffix></span>`
after mat-datetimepicker, inside mat-form-field.
