### ISSUE TITLE
Help needed - extract _activeDate on view change

### ISSUE THREAD

**Issue by samOpenforce** [kuhnroyal/mat-datetimepicker#146]
Hello! I understand this package is no longer maintained and so this is really a call for help to anybody out there who may be able to!

As the title suggests I'd like to extract the currently active date from the picker when the view changes. 

This is proving difficult as whilst the date used internally by the component updates the input does not and so binding to `(dateChange)` and `(dateInput)` does not give us what we need.

Any ideas on how to access this would be greatly appreciated!

Many thanks,

Sam

**Comment by bbortt** [comment]
hi @samOpenforce, i am currently busy with spring term exams. I can try figure something out next week, once I'm done with school.

I also plan to work on some issues here during my summer holiday 🚀

**Comment by samOpenforce** [comment]
Will close this as have found suitable solution. Many thanks all the same @bbortt , appreciate it!

**Comment by bbortt** [comment]
cool! can you post it here, in case someone has the same question? 🌈
