### ISSUE TITLE
Angular v12 support

### ISSUE THREAD

**Issue by micdenny** [kuhnroyal/mat-datetimepicker#147]
Is it possible to upgrade the `peerDependencies` to the latest angular v12?

**Comment by bbortt** [comment]
sure thing, give me a second! 🤣

**Comment by bbortt** [comment]
@micdenny published in [version `7.0.0`](https://www.npmjs.com/package/@mat-datetimepicker/core/v/7.0.0).

**Comment by bbortt** [comment]
and of course I fucked up the peer dependency of `core` in `moment`.. 🤦🏼 bugfix will follow shortly in `7.0.1`!

**Comment by micdenny** [comment]
Think about that people will think that the library it's more robust now that has already a patch, 7.0.1 feels better than 7.0.0 you test! 😂😂😂😂😂

**Comment by bbortt** [comment]
xD could you report me if everything works on angularV12 once you tested it?

**Comment by bbortt** [comment]
sorry, this did take me a little longer this time.. was already working on removing `tslint` and hat to joggle with multiple branches.. promised to do some work on this package - and will have some for the next few days :D
anyway, `7.0.1` is out.

**Comment by micdenny** [comment]
it works

![image](https://user-images.githubusercontent.com/1633595/125914129-a3e741ca-d54a-4f1a-bcd0-1c81752d6d35.png)

thank you
