### ISSUE TITLE
No way to change date label in header

### ISSUE THREAD

**Issue by JusuVh** [kuhnroyal/mat-datetimepicker#15]
Would be nice to be able to change the format of the **mat-datetimepicker-calendar-header-date** with a moment format for example.
I'm using localised formats and the date is kind of 'americanised'.
Thanks

**Comment by raualvron** [comment]
I agree with you @JusuVh.

Hopefully we can get it soon.

Thanks

**Comment by kuhnroyal** [comment]
Please review the PR and check if that is what you are looking for.

**Comment by kuhnroyal** [comment]
Released in 2.0.1.
