### ISSUE TITLE
"You provided 'undefined' where a stream was expected."

### ISSUE THREAD

**Issue by anton-simola-finnos** [kuhnroyal/mat-datetimepicker#151]
"@angular/animations": "^12.1.3",
    "@angular/cdk": "^12.1.3",
    "@angular/common": "12.1.3",
    "@angular/compiler": "12.1.3",
    "@angular/core": "12.1.3",
    "@angular/flex-layout": "^11.0.0-beta.31",
    "@angular/forms": "12.1.3",
    "@angular/material": "^12.1.3",
    "@mat-datetimepicker/core": "7.0.1",
    "@mat-datetimepicker/moment": "7.0.1",

Im getting this error when initializing the component (after angular upgrading):

TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

(below screenshot is from: class MatDatepickerToggle)
![image](https://user-images.githubusercontent.com/64903002/126950235-cae2b19b-3b4a-40e8-8345-6440944c5bfe.png)

**Comment by bbortt** [comment]
hi @anton-simola-finnos, am I right guessing that you used an angular v11 compatible version of `@mat-datetimepicker/core` with angular v12? the current release (`^9.0.0`) supports angular `^13.0.0`.

the error has been fixed in #148, I believe. please close the issue or provide further details.
