### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by leandromsa** [kuhnroyal/mat-datetimepicker#16]
Hello, there is some possibility of changing the format of the date?

**Comment by visurel** [comment]
Take a look at the DateAdapter! That's where all the magic happens. :)

**Comment by kuhnroyal** [comment]
You can provide a custom instance of `MatDatetimeFormats`.
```
const MY_CUSTOM_FORMATS: MatDatetimeFormats = { ... }
...
providers: [
  {
     provide: MAT_DATETIME_FORMATS,
     useValue: MY_CUSTOM_FORMATS
  }
]
```

These are the defaults depending if you use native and moment:
[native-datetime-formats.ts](https://github.com/kuhnroyal/mat-datetimepicker/blob/master/lib/core/src/adapter/native-datetime-formats.ts)
[moment-datetime-formats.ts](https://github.com/kuhnroyal/mat-datetimepicker/blob/master/lib/moment/src/adapter/moment-datetime-formats.ts)
