### ISSUE TITLE
Angular 13 - Support

### ISSUE THREAD

**Issue by Oryon86** [kuhnroyal/mat-datetimepicker#162]
Hi,

Is there any Angular 13 support for next version?

Thank you

**Comment by Qberon** [comment]
Upvote

code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ****@0.0.0
npm ERR! Found: @angular/cdk@13.0.3
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^13.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^12.1.0" from @mat-datetimepicker/core@7.0.1
npm ERR! node_modules/@mat-datetimepicker/core
npm ERR!   @mat-datetimepicker/core@"7.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by jakoujan** [comment]
some updates about this issue @kuhnroyal?

**Comment by bbortt** [comment]
the library is no longer actively maintained. I tried keeping it up to date, but have too much to do lately!

upgrading it to Angular v13 is a little task, you could contribute it 😉

**Comment by jakoujan** [comment]
thanks @bbortt i will do it as soon as i have some free time.

**Comment by bbortt** [comment]
release [`v8.0.0`](https://github.com/kuhnroyal/mat-datetimepicker/releases/tag/v8.0.0) is out now. thanks @LucaPezzato.
