### ISSUE TITLE
repository access

### ISSUE THREAD

**Issue by bbortt** [kuhnroyal/mat-datetimepicker#170]
hi @kuhnroyal, can you give me full access to this repository? I'd love to edit the secrets, so I can have a fully automated publish job to npmjs.org.

**Comment by bbortt** [comment]
see also #176.

**Comment by kuhnroyal** [comment]
Hey @bbortt, that is not possible without an organization.
But I can see what I can do about adding those secrets.

**Comment by kuhnroyal** [comment]
I added an `NPM` environment with a valid `NPM_TOKEN`.
Can be deployed to from `master` and `release` branch.

Let me know what else you need.

**Comment by bbortt** [comment]
thanks, that's ok then. can you add a `ACTION_TOKEN` with "repo" permission too? it's required for pushing version commits & tags.
both can be in the same environment (I ow for a general term e.g. "npmjs-release" or something) with access from withing the `release` branch. that's sufficent, I will remove the `master` afterwards.

**Comment by bbortt** [comment]
> I ow for a general term e.g. "npmjs-release" or something

actually I don't care that much.. `NPM` is fine too. I mean, it's an npm-only project, so.. 😅

**Comment by kuhnroyal** [comment]
If you want to remove the master branch then I'll make the release branch default?

**Comment by bbortt** [comment]
yes, that makes sense too. and apply some terms like "requires review and successful build", please.

**Comment by bbortt** [comment]
and if you're in the config anyway, can you activate GitHub Pages from `gh-pages` branch? I'll push a sample real quick..

**Comment by bbortt** [comment]
> I'll push a sample real quick..

done. the configuration is falsy, but you should be able to select the branch.

**Comment by bbortt** [comment]
@kuhnroyal #176 is ready when you are! 🚀
