### ISSUE TITLE
How to set locale in datebox (ex: ja-JP)

### ISSUE THREAD

**Issue by paulo3262** [kuhnroyal/mat-datetimepicker#20]
_**need to change the location of the date box, is in English, how to change this setting**_

![captura de tela de 2018-03-09 11-03-12](https://user-images.githubusercontent.com/17967366/37211075-8e1a0cf0-2389-11e8-9c63-2ceffa282582.png)

**Comment by kuhnroyal** [comment]
If you use moment you also need to add the moment locales that you need.
In `angular-cli` all locales are pulled in by default. If you use webpack or something else you might need to import them yourself.

https://github.com/moment/moment/issues/2416
https://github.com/moment/moment/issues/2608#issuecomment-336059877

Something like this might work
```
import 'moment/locale/ja';
```
