### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by tommueller** [kuhnroyal/mat-datetimepicker#21]
Hi,

running this in IE11 works, but the dialog cannot be closed anymore, also on selecting a date the popup does not close. Any chance this can be easily fixed?

Thanks!

**Comment by tommueller** [comment]
I managed to track down the issue and created a PR to show it. It's a IE specific bug with your refocus code, not sure if you want to remove it completely as I did for not.
https://github.com/kuhnroyal/mat-datetimepicker/pull/22

**Comment by kuhnroyal** [comment]
Fixed by 0e67e30b2734985b8dddaa72b03bf1dff70c6b84
