### ISSUE TITLE
Placeholder broken when ChangeDetection is used

### ISSUE THREAD

**Issue by Tommatheussen** [kuhnroyal/mat-datetimepicker#23]
When change detection is set to `OnPush` inside the component showing the datetimepicker, and a value is filled (prefilled or selected from the calendar), the placeholder does not move up like the normal material inputs. You can see this behaviour by running the demo and setting the chagnedetection on 1 of the components (native or moment).
<img width="879" alt="image" src="https://user-images.githubusercontent.com/13683094/38661834-78baa806-3e32-11e8-9b8d-428f25290a13.png">
After the field is clicked, the placeholder moves up and all is fine.

**Comment by ricardojbertolin** [comment]
Same here

**Comment by kuhnroyal** [comment]
Released in 2.0.1

**Comment by ricardojbertolin** [comment]
Tested in my project and working fine. Thank you!
