### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by johankvint** [kuhnroyal/mat-datetimepicker#25]
Hi,

Do you have any plans on updating this to angular 6?
I'm able to use this in my angular 6 project with rxjs-compat, but would be nice to skip that package.

Thanks

**Comment by johankvint** [comment]
https://github.com/kuhnroyal/mat-datetimepicker/pull/26

I made a minimal effort here to update to angular 6 but have not yet confirmed if it actually works to remove rxjs-compat.
Can someone help me confirm. Will hopefully be able to try later today.

**Comment by johankvint** [comment]
Have tested to build and use in a project using angular/material/rxjs 6 and it works fine

**Comment by kuhnroyal** [comment]
I may be able to get to this by the end of the week.
Any ideas about what version number you would like to see for this?

**Comment by johankvint** [comment]
@kuhnroyal I used a version of 2.0.0 in the package.json's as this will be a breaking change.
Do you want me to update the Readme as well?

**Comment by dannyhchan** [comment]
I'm planning to update to Angular 6 as well.  When will the new release package be out? Thanks

**Comment by Hyuchiha** [comment]
Hi, i want to update to angular 6, do you have any date for the update? Thanks

**Comment by kuhnroyal** [comment]
There is a version 2.0.0 out now, give it a try.
