### ISSUE TITLE
No option to put date ?

### ISSUE THREAD

**Issue by axiom88-guru** [kuhnroyal/mat-datetimepicker#28]
Thanks for great lib, 
Is there any way to put pre-defined date? 
dueDate is not empty value and but it always show empty. 

`<mat-datetimepicker-toggle [for]="datetimePicker" matSuffix></mat-datetimepicker-toggle>
 <mat-datetimepicker #datetimePicker type="datetime" openOnFocus="true" timeInterval="5"></mat-datetimepicker>
 <input matInput formControlName="dueDate" [matDatetimepicker]="datetimePicker" required autocomplete="false" placeholder="Due Date">`

**Comment by kuhnroyal** [comment]
Make sure the dueDate formControl contains a date instance. See https://github.com/kuhnroyal/mat-datetimepicker/issues/27
