### ISSUE TITLE
Using type=time, direct input is allowed but parsed as date

### ISSUE THREAD

**Issue by narthur157** [kuhnroyal/mat-datetimepicker#29]
If you use this just for the timepicker (I also use it for the datetimepicker of course), with Moment, it tries to convert input into the field into a date. So entering "12:35" will result in "null" because it's not a date.

**Comment by kuhnroyal** [comment]
Make sure you set the parse format or use the default formats `MAT_MOMENT_DATETIME_FORMATS`.
```
 parse: {
    timeInput: "LT"
  },
```

**Comment by narthur157** [comment]
Where do you set this? I use the default for my date format

**Comment by narthur157** [comment]
Nevermind, I see now, this is a separate option
