### ISSUE TITLE
Ability to choose year

### ISSUE THREAD

**Issue by bastienlemaitre** [kuhnroyal/mat-datetimepicker#3]
![image](https://user-images.githubusercontent.com/11610748/34409604-1334f626-ebcb-11e7-99a0-cf8cebcc929f.png)
Its possible to add a functionality to choose year ?
Thanks

**Comment by kuhnroyal** [comment]
You can click on the year and use the left/right chevrons to pick a year.

**Comment by bastienlemaitre** [comment]
A little complicated when you want to choose a date of birth.

**Comment by kuhnroyal** [comment]
I agree, I have the same problem but currently not the time to redesign this.

**Comment by bastienlemaitre** [comment]
Can we use any virtual scroll and add view for choosing year/month ? Can i do a pull request ?

**Comment by kuhnroyal** [comment]
Sure, if you find a good way that doesn't completely go against the current design.

**Comment by jpike88** [comment]
Wow just found out this doesn't even do year... it's not much of a date picker then! Time to look for an alternative

**Comment by benjaminflopez21** [comment]
A made a pull request https://github.com/kuhnroyal/mat-datetimepicker/pull/103 to add view for choosing year.

**Comment by bbortt** [comment]
released in `4.1.0`.
