### ISSUE TITLE
Any way to set a minimum date?

### ISSUE THREAD

**Issue by raualvron** [kuhnroyal/mat-datetimepicker#34]
It would be nice to be able to set a minimum date for mat-datetimepicker with a moment date

Thank you.

**Comment by kuhnroyal** [comment]
You can find an example here: https://github.com/kuhnroyal/mat-datetimepicker/blob/master/src/app/date.component.html

**Comment by raualvron** [comment]
Thank you for your quick response and the example @kuhnroyal.

**Comment by jcanning** [comment]
Is there any way to get this to work with the just the time? I have a requirement for "Booking Hours" where they are only open from 8:00 to 20:00. So that those are the only hours to show?
