### ISSUE TITLE
Upgrading to angular 14

### ISSUE THREAD

**Issue by tbrandenburger** [kuhnroyal/mat-datetimepicker#342]
Hi,

I've got peer dependencies error while upgrading to angular 14 and angular material 14.

 Could not resolve dependency:
npm ERR! peer @angular/cdk@"^13.1.1" from @mat-datetimepicker/core@9.0.68

**Comment by bbortt** [comment]
I've checked like a month ago and because of some third party dependencies we were not ready back then. will retry rightnow.

**Comment by bbortt** [comment]
@tbrandenburger angular v14 support was released in [`v10.0.0`](https://github.com/kuhnroyal/mat-datetimepicker/releases/tag/v10.0.0).
