### ISSUE TITLE
Will it work with angular-4 and material-2.0.0.12-beta

### ISSUE THREAD

**Issue by JackieManuja** [kuhnroyal/mat-datetimepicker#4]
Thanks for the great component! 👍 

Will it work with angular 4 and material 2.0.0.12-beta?

**Comment by kuhnroyal** [comment]
No, this is based on angular/material 5.

**Comment by JackieManuja** [comment]
I have a project with Angular 4 and Angular-material-2.0.0.12-beta, any workaround to use this component?

**Comment by kuhnroyal** [comment]
No, this component requires the datepicker base classes that came later somewhere in material 5.0.0-rcX.
Which in turn requires angular 5.
