### ISSUE TITLE
Unable to change month when day index is outside bounds

### ISSUE THREAD

**Issue by rebendajirijr** [kuhnroyal/mat-datetimepicker#40]
**Steps to reproduce:**

1. Choose some date which is last day of month (e.g. 31 days long months - January, March, etc.)
2. Now try to change the selected month to a month with less days in total (like February).
3. Error appears due to this [line](https://github.com/kuhnroyal/mat-datetimepicker/blob/2.0.1/projects/moment/src/adapter/moment-datetime-adapter.ts#L98).

![image](https://user-images.githubusercontent.com/3431185/43472980-2f27eeb0-94ef-11e8-8832-2e0e15852aea.png)

**Expected result:**

Month is properly set with no error and user must reselect the day to complete the change.

**Comment by kuhnroyal** [comment]
Please review #59

**Comment by bbortt** [comment]
Approved and merged in #59 .
