### ISSUE TITLE
Angular 15 not supported

### ISSUE THREAD

**Issue by ricardojbertolin** [kuhnroyal/mat-datetimepicker#403]
Hi,

I've tried to install in an A15 project and got the following error: 

`npm ERR! peer @angular/cdk@"^14.0.4" from @mat-datetimepicker/core@10.0.10`

Will you support Angular 15 soon?

Thank you

**Comment by bbortt** [comment]
@ricardojbertolin well, you could submit a PR bumping the `peerDependency`s ;)

**Comment by ricardojbertolin** [comment]
Nice, I'll do!

**Comment by gsontag** [comment]
I made a PR for this issue https://github.com/kuhnroyal/mat-datetimepicker/pull/404

**Comment by ricardojbertolin** [comment]
Thank you very much @gsontag

**Comment by ricardojbertolin** [comment]
I see you have merged a PR with the A15 support. Good job @gsontag !

I wonder @bbortt why there isn't new version available. I had to install the package from your repo directly to make it work. Are you considering launching a new release soon?

Meanwhile I'm going to try it out in my project, I'll give you feedback soon. 
Thank you very much!

**Comment by bbortt** [comment]
@ricardojbertolin there were two issues regarding the release, both being addressed in https://github.com/kuhnroyal/mat-datetimepicker/pull/405.

**Comment by bbortt** [comment]
well, good news. `v11.0.0` hast just been released! good luck :)
