### ISSUE TITLE
Dependency Inconsistency

### ISSUE THREAD

**Issue by elkhouri** [kuhnroyal/mat-datetimepicker#41]
`npm WARN @mat-datetimepicker/moment@2.0.1 requires a peer of @mat-datetimepicker/core@2.0.0 but none is installed.`

I have @mat-datetimepicker/moment@2.0.1 and @mat-datetimepicker/core@2.0.1 installed. It seems there is a inconsistency in the dependency versions. Or is this intended?

**Comment by kuhnroyal** [comment]
Nah, I keep forgetting to update the version in the moment module...
