### ISSUE TITLE
BC released in a minor

### ISSUE THREAD

**Issue by TomasHubelbauer** [kuhnroyal/mat-datetimepicker#412]
Hi, you cut `10.1.0` after updating Angular major and that seems to be a breaking change. You cut `11.0.0` shortly after but for people who have `^10.0.10` they will see `10.1.0` a change which I think should have a corresponding major break. Would it be possible to pull 10.1.0 off NPM so people with `^10.0.10` remain unbroken and they can bump to v11 on their own? Thanks

**Comment by kuhnroyal** [comment]
@bbortt are there any other changes in this version?

**Comment by kuhnroyal** [comment]
So the `10.1.0` is no longer in the registry or on Github (only the tag remains). It was removed yesterday.
See https://github.com/kuhnroyal/mat-datetimepicker/pull/405#issuecomment-1332445377

**Comment by bbortt** [comment]
@kuhnroyal yes, sadly I couldn't remove it from npmjs.org: https://www.npmjs.com/package/@mat-datetimepicker/core/v/10.1.0. I actually think that is because `v11.0.0` was already published "over it".

**Comment by TomasHubelbauer** [comment]
I believe NPM support should be able to pull the package if you explain the situation.

**Comment by bbortt** [comment]
question is if that is necessary. yes, it's uncool to have a minor with a breaking change (and it was completly my fault). but I think most people will let something like @dependabot handle their dependencies, so that will in most cases not be a problem.

**Comment by TomasHubelbauer** [comment]
I don't know, I can only share anecdata and in my case I was motivated to make this issue because a client of mine who had `^10.0.10` started seeing failures in their pipeline which resulted in an incident for the on-call team (hello!). Of course, the consumer of the package is always responsible for reviewing their dependencies, even if they didn't make any changes because the open range with the caret resulted in a version jump without them having to change the dependency version explicitly, so while I don't think any of the blame lies on you, depending on how many consumers there are for the package, yanking the package could save other users' time if they have the same open version range. IME the caret ranges are common so I am inclined to consider yanking the bad version a good idea, but the final call is of course yours.

**Comment by bbortt** [comment]
that's a good one haha I'm sorry to hear that. but glad you caught it in the pipeline, not the production ;)

well, there's a lot of people out there still using bad practice regarding `npm install` and all the risks coming with it. maybe also just not being aware of the risks. in the end, it's a consumer problem. but I see that of course not everyone will have pipelines (not even speaking of tests) catching these issues.

anyway, I still think deleting it will be hard. what do you think of another `10.0.11` version? so the "latest" of `>11` will be clean, at least. just throwing that into the room, must think about it for a minute.

**Comment by TomasHubelbauer** [comment]
I think it would have to be `10.1.1`, right? To beat `10.1.0` which we got from `^10.0.10`. It sounds like a good idea on face value, unless there are problems with it that I am not seeing, I think that would pretty much erase the potential harm altogether, because people's `^10.0.10` (or even `^10`) would resolve to the fixed `10.1.1` which would be the same as `10.0.10` and no problem would occur. Did I understand this correctly?

Anyway, if this solution ends up not being applicable for whatever reason and deleting the broken version proves tricky, I think that's not the end of the world. Definitely don't lose sleep over it, I think we agree that at the end of the day it's the users who are responsible for what they ship. It's just a tradeoff between how much time and effort you want to spend to make it easy for folks versus how much responsibility we want to leave to them to learn to audit their deps. :-)

**Comment by bbortt** [comment]
I think I can make a release version `10.0.11` just for npmjs.com that would be sufficient.

**Comment by bbortt** [comment]
ah yea `10.1.1` I mean. it was a `feat` commit, never mind.

**Comment by kuhnroyal** [comment]
Yea, thats a good idea. And also deprecate `@mat-datetimepicker/core@10.1.0`.
You seem to already have deprecated the moment version: https://www.npmjs.com/package/@mat-datetimepicker/moment/v/10.1.0

**Comment by bbortt** [comment]
@kuhnroyal wait what, I thought that didn't work. I remember the command line returning an error code. anyway, glad that actually worked. I'll do that too for `@mat-datetimepicker/core` then: https://www.npmjs.com/package/@mat-datetimepicker/core/v/10.1.0.

---
and for the records:
* I checked out the repository @ `v10.0.10`
* I've run `npm ci`
* I've bumped the versions, resulting in the following diff (fixed `peerDependency` for the `@mat-datetimepicker/moment` adapter):
```shell
$ git diff
diff --git a/projects/core/package.json b/projects/core/package.json
index a128b48..455191a 100644
--- a/projects/core/package.json
+++ b/projects/core/package.json
@@ -1,6 +1,6 @@
 {
   "name": "@mat-datetimepicker/core",
-  "version": "10.0.10",
+  "version": "10.1.1",
   "repository": "https://github.com/kuhnroyal/mat-datetimepicker.git",
   "author": "PL <kuhnroyal@gmail.com>",
   "license": "MIT",
diff --git a/projects/moment/package.json b/projects/moment/package.json
index 1e91e46..9c4e932 100644
--- a/projects/moment/package.json
+++ b/projects/moment/package.json
@@ -1,6 +1,6 @@
 {
   "name": "@mat-datetimepicker/moment",
-  "version": "10.0.10",
+  "version": "10.1.1",
   "repository": "https://github.com/kuhnroyal/mat-datetimepicker.git",
   "author": "PL <kuhnroyal@gmail.com>",
   "license": "MIT",
@@ -10,7 +10,7 @@
     "@angular/core": "^14.0.5",
     "@angular/material": "^14.0.4",
     "@angular/material-moment-adapter": "^14.0.4",
-    "@mat-datetimepicker/core": "^10.0.0"
+    "@mat-datetimepicker/core": "10.1.1"
   },
   "dependencies": {
     "tslib": "^2.4.0"
```
* next, I ran `npm run build:lib`
* and then published the backport/fix release
  * `npm publish ./dist/core && npm publish ./dist/moment`
* and because I'm a dumbass and forgot that npmjs.org does not respect SemVer, I had to adjust the `latest` tags using `npm dist-tag add @mat-datetimepicker/core@11.0.0 latest && npm dist-tag add @mat-datetimepicker/moment@11.0.0 latest` for the final step

**Comment by kuhnroyal** [comment]
Yea the unpublish didn't work, I tried that myself. But the deprecation seems to have worked, nice job!
