### ISSUE TITLE
mat-datetimepicker production mode

### ISSUE THREAD

**Issue by eromano** [kuhnroyal/mat-datetimepicker#42]
Hi I am tryng to use the last version 2.0.1 in production mode and seems that the calendar day are nor present 
![screen shot 2018-08-10 at 11 21 51](https://user-images.githubusercontent.com/1030050/43953059-befe5d7e-9c8f-11e8-8191-62888d09ed6e.png)

**Comment by kuhnroyal** [comment]
I have no idea, is this still a problem?
The example app in this repository works fine with  `ng serve --prod`.

**Comment by bbortt** [comment]
agree with @kuhnroyal, the sample application works in productive mode. @eromano please re-report with a reproducible sample if the problem still exists using the latest version.
