### ISSUE TITLE
Working Demo

### ISSUE THREAD

**Issue by gkimpson** [kuhnroyal/mat-datetimepicker#48]
This plugin seems great - I just wondered if someone had a working demo of this so I can determine at a glance if this is what I need for my next project? Thanks in advance

**Comment by sgabb** [comment]
Here is a small demo of the component: https://angular-vesksm-x5zk8x.stackblitz.io/

**Comment by bbortt** [comment]
for anyones information: the new pipeline does also publish the sample application to GitHub pages for each release.

url: https://kuhnroyal.github.io/mat-datetimepicker/.
