### ISSUE TITLE
@mat-datetimepicker/moment peerDependency 

### ISSUE THREAD

**Issue by derflocki** [kuhnroyal/mat-datetimepicker#49]
@mat-datetimepicker/moment defines a peerDependency to `"@mat-datetimepicker/core": "2.0.0"`.

The [npm-blog](https://nodejs.org/en/blog/npm/peer-dependencies/#using-peer-dependencies) suggests using semver for peerDependencies: E.g.: `"@mat-datetimepicker/core": "^2.0.0"`

**Comment by kuhnroyal** [comment]
I disagree, peer dependencies of the same library need to be a fixed version. `moment-2.0.1` needs exactly `core-2.0.1` and not some other future version.

**Comment by bbortt** [comment]
since we brought semver into the picture, and in terms of conventional commits, i agree with @derflocki. i have adjusted the peer dependency accordingly: [source](https://github.com/kuhnroyal/mat-datetimepicker/blob/v9.0.0/projects/moment/package.json#L13).
