### ISSUE TITLE
Can't set value with datetime

### ISSUE THREAD

**Issue by bastienlemaitre** [kuhnroyal/mat-datetimepicker#5]
When i set the value into my form, the minutes and seconds are not displayed.. Any reason ?

View:
![image](https://user-images.githubusercontent.com/11610748/34715564-5bc41e06-f52d-11e7-94a2-c07ada830854.png)

Code;
![image](https://user-images.githubusercontent.com/11610748/34715589-6b10afbe-f52d-11e7-8e3f-f2d41e85b42a.png)

Code inline 
```ts
const startDate = new Date(delegation.StartDate);
const endDate = new Date(delegation.EndDate);
console.log(startDate, endDate);
this.delegationForm.get('startDate').setValue(startDate);
this.delegationForm.get('endDate').setValue(endDate);
this.delegationForm.get('sendEmail').setValue(delegation.SendEmail);
this.delegationForm.get('sendEmailToSignatory').setValue(delegation.SendEmailToSignatory);
```

Console:
![image](https://user-images.githubusercontent.com/11610748/34715612-7e483ba6-f52d-11e7-840f-aaea478d9b61.png)

**Comment by kuhnroyal** [comment]
You need to set the type `type="datetime"` as shown in the README. The default is `date`.

**Comment by bastienlemaitre** [comment]
Is already set to type="datetime"..

**Comment by kuhnroyal** [comment]
Please try to provide an example that reproduces the issue. Than I can reopen and look at it. For more I don't have the time. Plunkr, Stackblitz etc.

**Comment by bastienlemaitre** [comment]
Found why..
https://angular-material-datetimepicker-issue.stackblitz.io

The matInput must be declared after mat-datetime-picker

**Comment by kuhnroyal** [comment]
Fixed in 1.0.2: https://stackblitz.com/edit/angular-material-datetimepicker-issue-1czu9e

**Comment by bastienlemaitre** [comment]
Thanks !

**Comment by jac0117** [comment]
@bastienlemaitre's solution worked for me.
