### ISSUE TITLE
view change event

### ISSUE THREAD

**Issue by tomas-javurek** [kuhnroyal/mat-datetimepicker#50]
Great job @kuhnroyal !!
Please, is there any way how to get some change event while the View "clock" | "month" | "year" switched by user?
It would be probably good for the date filtering. Now it is so that the year and month views trigger the time with the current hours and minutes. Which is, for sure, absolutely right, but what about the case I need to filter date only on the clock view?

**Comment by kuhnroyal** [comment]
Please review #58

**Comment by Hyuchiha** [comment]
Any news on this feature?

**Comment by bbortt** [comment]
someone needs to test #58 . would be willing to include it in the next release if someone approves the changes.

**Comment by DenysVuika** [comment]
I checked the PR and it seems to be ok.
