### ISSUE TITLE
Support Angular 17

### ISSUE THREAD

**Issue by Talb2005** [kuhnroyal/mat-datetimepicker#503]
When updating Angular to version 17, I'm getting the following message: 
`Package "@mat-datetimepicker/core" has an incompatible peer dependency to "@angular/material" (requires "^16.2.0", would install "17.0.0").`

**Comment by bbortt** [comment]
damn, angular is moving fast. 17 being out already? well, PR's are welcome. l think it should be almost compatible without further ado!

**Comment by Tweniee** [comment]
@bbortt does this looks good

**Comment by bbortt** [comment]
> @bbortt does this looks good

gave you feedback. looks good in general.

**Comment by bbortt** [comment]
https://github.com/kuhnroyal/mat-datetimepicker/releases/tag/v13.0.0
