### ISSUE TITLE
Wrong Dependency on @mat-datetimepicker/moment

### ISSUE THREAD

**Issue by weckx** [kuhnroyal/mat-datetimepicker#511]
The `@mat-datetimepicker/moment` package has a dependency on `@mat-datetimepicker/core: ^12.0.0` which causes an error when using NPM install. I believe it should be updated to `@mat-datetimepicker/core: ^13.0.0`

**Comment by bbortt** [comment]
damn. missed that. let's see if I find time to fix it this evening. if you're faster @weckx, feel free to open a PR.

**Comment by weckx** [comment]
Was going to work on it right now, but I see you just fixed it. Thanks!
