### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by rebendajirijr** [kuhnroyal/mat-datetimepicker#54]
Could you please add support for Angular 7?

**Comment by kuhnroyal** [comment]
Added `3.0.0-beta.0` built on angular/material 7.1 - give it a try.

**Comment by spiraljacobs** [comment]
Is 3.0.0-beta.0 up on NPM?  What about for ng-pick-datetime-moment?

**Comment by Fieel** [comment]
> 3.0.0-beta.0

Where can i find this? It's nowehere to be found. When will 3.0.0 be released btw? Thank you for your work man.

**Comment by Luminoth** [comment]
Any chance we'll see this move out of beta soon?

**Comment by q158467234** [comment]
Does angular 7.0 support usage?

**Comment by bbortt** [comment]
bumped core to `angular/v8` in #73 .
