### ISSUE TITLE
Can't update to Angular 18

### ISSUE THREAD

**Issue by Talb2005** [kuhnroyal/mat-datetimepicker#555]
Executing ng update @angular/cdk @angular/material results in:
```
Package "@mat-datetimepicker/core" has an incompatible peer dependency to "@angular/cdk" (requires "^17.0.0", would install "18.0.0").
Package "@mat-datetimepicker/core" has an incompatible peer dependency to "@angular/material" (requires "^17.0.0", would install "18.0.0").
```

**Comment by bbortt** [comment]
someone would have to upgrade the repo (especially `peerDependencies`) first.

**Comment by Talb2005** [comment]
I have created a PR. https://github.com/kuhnroyal/mat-datetimepicker/pull/563
Please review it.

**Comment by bbortt** [comment]
will do, many thanks!

**Comment by Negodyaj** [comment]
I'm sorry, but any ETA on this?...)

**Comment by Negodyaj** [comment]
thanks so much!! )
