### ISSUE TITLE
Time & Minutes disabled but able to select it.

### ISSUE THREAD

**Issue by dannyhchan** [kuhnroyal/mat-datetimepicker#6]
When setting [min]="1/11/2018 3:00 AM", the UI shows 1:00 AM and 2:00 AM as disabled on the same date.  Even in disabled state, you can click and select times before 3:00 AM even though [min] shows 3:00 AM as minimum time.

Attached is a screen shot.
![datetime-picker-bug](https://user-images.githubusercontent.com/8468808/34798705-25b95b92-f62b-11e7-95d8-2f200862edc7.PNG)

**Comment by bastienlemaitre** [comment]
Please create a demo on plunker or stackblitz.

**Comment by kuhnroyal** [comment]
I will try to take a look at this on the weekend.

**Comment by kuhnroyal** [comment]
Able to reproduce this.

**Comment by kuhnroyal** [comment]
Fixed in 1.0.2

**Comment by dannyhchan** [comment]
Thank you!

**Comment by dannyhchan** [comment]
Kuhnroyal,
I installed the latest and noticed another issue now.  I set the [min] with return moment().  My current local time is 1/15/2018 11:00 AM, and the rest of the times are blocked off thinking is 11:00 PM.  

I have attached a screen shot.  As you can see, I display the datetime on top of the field the value I'm passing into [min].  And 1 PM, 2 PM, etc is blocked off.

![datetime-picker-bug](https://user-images.githubusercontent.com/8468808/34952059-5f14c70a-f9e6-11e7-956d-087b4546f8b0.PNG)

Thank you.

**Comment by kuhnroyal** [comment]
This is a 24 hour clock. There is currently no AM/PM mode.
1AM = 1
1PM = 13

**Comment by dannyhchan** [comment]
Understood. The problem is I can't select anything beyond 12.  The min time
I have is 1/15/2018 11:22:08 GMT-500.  I cannot select 1/15/2018 13:00,
14:00 etc.  The min is the minimum time to start at with no max set, so I
should be able to select 13,14, etc.

Hope that clarified it.

**Comment by kuhnroyal** [comment]
Ah ok, got it

**Comment by kuhnroyal** [comment]
Just tried real quick and can not reproduce this in my timezone. Can you setup a plunkr/stackblitz that reproduces this?

**Comment by dannyhchan** [comment]
Just checked it's my fault.  The webpack i was using never compiled that
bundle properly.  So I redid it and it works fine now.  Thanks again!
