### ISSUE TITLE
Compatibility with Angular 19

### ISSUE THREAD

**Issue by halimamouchrif** [kuhnroyal/mat-datetimepicker#614]
Hello, 
After migrating to angular 19, I started having these errors
warning " > @mat-datetimepicker/core@14.0.0" has incorrect peer dependency "@angular/cdk@^18.0.3".
warning " > @mat-datetimepicker/core@14.0.0" has incorrect peer dependency "@angular/common@^18.0.3".
warning " > @mat-datetimepicker/core@14.0.0" has incorrect peer dependency "@angular/core@^18.0.3".
warning " > @mat-datetimepicker/core@14.0.0" has incorrect peer dependency "@angular/material@^18.0.3".
warning " > @mat-datetimepicker/moment@14.0.0" has incorrect peer dependency "@angular/cdk@^18.0.3".
warning " > @mat-datetimepicker/moment@14.0.0" has incorrect peer dependency "@angular/common@^18.0.3".
warning " > @mat-datetimepicker/moment@14.0.0" has incorrect peer dependency "@angular/core@^18.0.3".
warning " > @mat-datetimepicker/moment@14.0.0" has incorrect peer dependency "@angular/material@^18.0.3".
warning " > @mat-datetimepicker/moment@14.0.0" has incorrect peer dependency "@angular/material-moment-adapter@^18.0.3".

Thank you in advance.

**Comment by bbortt** [comment]
that is true, the project currently only supports angular 18. I can take a look at this at the weekend, probably.

feel free to upgrade the project and submit a PR in the meantime, if you feel like it.

**Comment by aalbericio** [comment]
I'm also facing this issue. 

Thanks in advance!

**Comment by bbortt** [comment]
I've resolved this issue, but the release pipeline is failing. I have a feeling that `GH_PAT` is no longer valid @kuhnroyal.

pipeline reference: https://github.com/kuhnroyal/mat-datetimepicker/actions/runs/12236439408/job/34130232629.

**Comment by kuhnroyal** [comment]
I updated the token and published the release.
Thank you @bbortt!
