### ISSUE TITLE
Angular 8

### ISSUE THREAD

**Issue by alessiostalla** [kuhnroyal/mat-datetimepicker#69]
Support Angular version 8.x

**Comment by alessiostalla** [comment]
At a quick glance, nothing needs to be done. The component seems to work as is.

**Comment by DenisaSurdu** [comment]
Hi I'm trying to upgrade my Angular 7 project to Angular 8 and I get the following: 
```
                  Package "@mat-datetimepicker/core" has an incompatible peer dependency to "@angular/core" (requires "^6.0.7" (extended), would install "8.0.2").
                  Package "@mat-datetimepicker/core" has an incompatible peer dependency to "@angular/cdk" (requires "^6.3.3", would install "8.0.1").
                  Package "@mat-datetimepicker/moment" has an incompatible peer dependency to "@angular/material-moment-adapter" (requires "^6.3.3", would install "8.0.1").
                  Package "@mat-datetimepicker/core" has an incompatible peer dependency to "@angular/material" (requires "^6.3.3", would install "8.0.1").

Incompatible peer dependencies found. See above.
```

**Comment by alessiostalla** [comment]
@DenisaSurdu I think you can safely ignore those warnings. At least, in my project everything works despite those being raised. Still, if the library were updated to avoid them, it would be better.

**Comment by DenisaSurdu** [comment]
@alessiostalla @kuhnroyal I've opened a pull request for this https://github.com/kuhnroyal/mat-datetimepicker/pull/72

**Comment by alessiostalla** [comment]
@DenisaSurdu @kuhnroyal no progress is being made on this. Angular 9 is in the making. If you need help in maintaining the project I am willing to do it.

**Comment by DenisaSurdu** [comment]
@alessiostalla I can't merge the pull request because merging is blocked - the base branch requires all commits to be signed ( https://help.github.com/en/articles/about-commit-signature-verification ) and I don't know how to go around this.

**Comment by bbortt** [comment]
The merge was finished using the releases as uppon 2019/08/29.
