### ISSUE TITLE
Does not implement inherited abstract member 'fromIso8601'

### ISSUE THREAD

**Issue by npdung** [kuhnroyal/mat-datetimepicker#7]
With  `"@angular/material": "^2.0.0-beta.12"`

I have error when build 
![image](https://user-images.githubusercontent.com/10497117/34809168-de58f208-f6c5-11e7-983e-e8c5d52a1f74.png)

**Comment by bastienlemaitre** [comment]
Please install Angular > 5.0 and Material > 5.0 because "Material Datetimepicker for @angular/material 5.x"

**Comment by kuhnroyal** [comment]
Yes, this doesn't work with the 2.x.x-betas.
