### ISSUE TITLE
Unredeable header css

### ISSUE THREAD

**Issue by mateuszbyczkowski** [kuhnroyal/mat-datetimepicker#71]
.mat-datetimepicker-calendar-header has #fff color, identical to it's default background. 
With default theme it's impossible to chosen datetime because it's white on white background.
It would be nice to make it customizable or to delete this css and let it inherit.

**Comment by mateuszbyczkowski** [comment]
Example to issue. 
![Capture](https://user-images.githubusercontent.com/17723906/60012847-425d4d00-967d-11e9-9d60-6cd1a81c14ab.PNG)

**Comment by 695Multimedia** [comment]
I'm seeing this same issue. Any progress on this?

**Comment by bbortt** [comment]
Hi guys. The project is currently "kind of maintained". I'm happy to accept PR's all the time. However I cannot find to implement features or fix bugs. In fact, I still didn't even found the time to fix the build (it's `angular/v8`) or to upgrade the angular version (`angular/v9` beta).

**Comment by DenysVuika** [comment]
@bbortt I can help contributing and maitaining if you need an extra pair of hands :)

**Comment by bbortt** [comment]
That'd be great! I mean I can accept PRs and push releases at any time, that's a matter of minutes. But my company does no longer use this project, so there's no time investment possible from this side. And I'm (sadly) pretty busy otherwise.

**Comment by moritzluedtke** [comment]
Without taking a deep dive into this, I found this line of code:
https://github.com/kuhnroyal/mat-datetimepicker/blob/release/projects/core/src/datetimepicker/calendar.scss#L26

I think that should go away. When I remove this exact `color` property in the dev console in the browser the colors go back to normal. The elements even have different colors. So I think this just incorrectly overwrites them.

I would test this out but I have no experience in testing/developing JS libraries. Maybe someone else can test this?

**Comment by bbortt** [comment]
@moritzluedtke I will take a look at it by the end of the week.. thanks for the hint.
