### ISSUE TITLE
project not maintained

### ISSUE THREAD

**Issue by bbortt** [kuhnroyal/mat-datetimepicker#76]
hello @kuhnroyal 
it seems like this project is unmaintained at the moment. especially because of #73 is open since decades (at least it feels like it).
I would be willing to fork, distribute and maintain it further if you agree with it. thanks for your feedback.
br, timon

**Comment by kuhnroyal** [comment]
I dunno if and when I will have time to work on this again. So for the time being, I have added you as collaborator here and on https://www.npmjs.com/org/mat-datetimepicker. Feel free to manage and release in the meantime.

**Comment by bbortt** [comment]
thank you very much. I'll give my best
