### ISSUE TITLE
fix build, release

### ISSUE THREAD

**Issue by bbortt** [kuhnroyal/mat-datetimepicker#77]
As soon as the build will be fixed, we're ready to release an `angular/v8` compatible version. I'll try to take a look at it by the end of the week.
Contributions welcome as always.

**Comment by shadowjustice** [comment]
Hi,

Has there been any progress towards this release?

Thank you.

**Comment by shadowjustice** [comment]
> Hi,
> 
> Has there been any progress towards this release?
> 
> Thank you.

In a sense to try and fix this myself I have tried first by updating all v8 versions to the latest available. Sadly no solution.

**Comment by bbortt** [comment]
I should be able to release a build based on commit c0a70499c1e3002abd563fff616e681ec57caa1c this weekend.
