### ISSUE TITLE
in angular 5.2.0 error

### ISSUE THREAD

**Issue by xyezir** [kuhnroyal/mat-datetimepicker#8]
![image](https://user-images.githubusercontent.com/5794890/34887794-b3beb97c-f802-11e7-9128-7e5ce163085d.png)

**Comment by bastienlemaitre** [comment]
Try 
```sh 
npm cache clear & npm i -f
```

**Comment by kuhnroyal** [comment]
Not sure, I can run it with angular 5.2.0. Need more information.

**Comment by xyezir** [comment]
Its ok, but i need npm i @angular/material-moment-adapter, document did not say.

**Comment by kuhnroyal** [comment]
Added a line to the README.
