### ISSUE TITLE
V 3.0.1 published /core package inconsistent peer deps

### ISSUE THREAD

**Issue by JonathanWylie** [kuhnroyal/mat-datetimepicker#86]
I get this error

npm WARN @mat-datetimepicker/core@3.0.1 requires a peer of @angular/material@~8.1.4 but none was installed.

According to the git history: 
https://github.com/kuhnroyal/mat-datetimepicker/commit/895f3185662f2f4de50d0b9c018f25573e44c639

Introduces version 3.0.1 it changed
    "@angular/cdk": "~8.1.4",	    "@angular/cdk": "~8.2.3",
but leaves angular/material at ~8.1.4
    "@angular/material": "~8.1.4"	    "@angular/material": "~8.1.4"

That is inconsistent though, presumably it was just an oversight and the angular/material dep was meant to be changed too, just as it was in the /moment package.

**Comment by bbortt** [comment]
Thanks for the report! I missed those and will publish a fix `3.0.2` right away.
By the way tag `4.0.0` should be the latest version but is not tagged as `latest` on npm. I will have to retag this too.

**Comment by bbortt** [comment]
Thanks again @JonathanWylie. Version `3.0.2` was published moments ago. Let me know if there are any more troubles.

**Comment by JonathanWylie** [comment]
Thanks all fine now, I am using angular 8, so I think version 4.0.0 won't work.
