### ISSUE TITLE
Accessible name is not meaningful for Next and Previous elements in year view

### ISSUE THREAD

**Issue by DenysVuika** [kuhnroyal/mat-datetimepicker#90]
Currently, the screen reader announce it as previous and next month instead of previous and next year.

<img width="849" alt="Screenshot 2020-03-26 at 14 32 39" src="https://user-images.githubusercontent.com/503991/77658824-2588d980-6f6f-11ea-922c-7018ba6a073e.png">

**Expected behavior**
Ensure that accessible name is meaningful for the mentioned elements

**Comment by DenysVuika** [comment]
I am working on the PR to fix this issue for the 3.x branch

**Comment by bbortt** [comment]
Fixed in #91 . Thanks @DenysVuika .
